//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5448
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMPMMLEditor7 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MMLEditorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MMLEditorResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMPMMLEditor7.MMLEditorResource", typeof(MMLEditorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FMP7 MML Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   80 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultEditor_TextWidth {
            get {
                return ResourceManager.GetString("DefaultEditor_TextWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＭＳ ゴシック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultFont_FontFamiliyName {
            get {
                return ResourceManager.GetString("DefaultFont_FontFamiliyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   12 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultFont_FontSize {
            get {
                return ResourceManager.GetString("DefaultFont_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP7 の起動に失敗しました。
        ///FMP&apos; へのパスが正しく設定されているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailedStartupFMP {
            get {
                return ResourceManager.GetString("Error_FailedStartupFMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常な FMC モジュールではありません。{0} 以上の FMC を使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FMCModule {
            get {
                return ResourceManager.GetString("Error_FMCModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非対応バージョンの FMC です。{0} 以上の FMC を使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FMCVersion {
            get {
                return ResourceManager.GetString("Error_FMCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP7 の起動が確認できませんでした。
        ///FMP7 へのパスが正しく設定されているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FMPNotAvailable {
            get {
                return ResourceManager.GetString("Error_FMPNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンパイラモジュール(fmc.dll)のロードに失敗しました。
        ///設定画面で再度設定を行ってください。
        ///正しく設定で行われていない場合はコンパイルが実行できません。
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_LoadCompilerModule {
            get {
                return ResourceManager.GetString("Error_LoadCompilerModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンパイラモジュールが初期化されていません。
        ///コンパイラモジュール(fmc.dll)へのパスが正しく設定されているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotInitializedCompiler {
            get {
                return ResourceManager.GetString("Error_NotInitializedCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMC7 モジュールファイル(fmc*.dll)|fmc*.dll|全てのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilter_FMC7DLL {
            get {
                return ResourceManager.GetString("FileFilter_FMC7DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP7 実行ファイル(FMP*.exe)|FMP*.exe|全てのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilter_FMP7EXE {
            get {
                return ResourceManager.GetString("FileFilter_FMP7EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP7 MMLファイル(*.mwi)|*.mwi|FMP(98) MMLファイル(*.mpi;*.mvi;*.mzi)|*.mpi;*.mvi;*.mzi|全てのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileFilter_MML {
            get {
                return ResourceManager.GetString("FileFilter_MML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンベロープ数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_Envelop {
            get {
                return ResourceManager.GetString("FileInfo_Envelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_FileName {
            get {
                return ResourceManager.GetString("FileInfo_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM(OPM)パート数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_PartOPM {
            get {
                return ResourceManager.GetString("FileInfo_PartOPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM(OPNA)パート数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_PartOPNA {
            get {
                return ResourceManager.GetString("FileInfo_PartOPNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PCMパート数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_PartPCM {
            get {
                return ResourceManager.GetString("FileInfo_PartPCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSGパート数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_PartSSG {
            get {
                return ResourceManager.GetString("FileInfo_PartSSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パート総数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_PartTotal {
            get {
                return ResourceManager.GetString("FileInfo_PartTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM音色数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_ToneFM4 {
            get {
                return ResourceManager.GetString("FileInfo_ToneFM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAVE数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileInfo_WavePCM {
            get {
                return ResourceManager.GetString("FileInfo_WavePCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fmc.dll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FMC7DllName {
            get {
                return ResourceManager.GetString("FMC7DllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP7.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FMP7ProgramName {
            get {
                return ResourceManager.GetString("FMP7ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無題 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP\FMP7 MML Editor\FMPMMLEditor7Setting.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFile {
            get {
                return ResourceManager.GetString("SettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.aosoft.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URL_AOSoft {
            get {
                return ResourceManager.GetString("URL_AOSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://azuki.sourceforge.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URL_Azuki {
            get {
                return ResourceManager.GetString("URL_Azuki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.fmp.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URL_FMP {
            get {
                return ResourceManager.GetString("URL_FMP", resourceCulture);
            }
        }
    }
}
